### ISSUE TITLE
[auth0-related] "Error: domain option is required" when running "npm start" and "setup.bash" does not exist in repo

### ISSUE THREAD

**Issue by rubenanapu** [gazebo-web/gazebosim-app#12]
Hi @nkoenig and @german-e-mas,

I've been trying to serve this app locally but I'm having problems following the instructions, but I could not find the **setup.bash** file mentioned in the instructions.

When I try to serve the app with `npm start` I get a blank page on http://localhost:3000/, and the **JavaScript Developer Tools** say:
```
core.js:4352 ERROR Error: domain option is required
    at attribute (auth0.min.esm.js:8:45247) [angular]
    at Object.check (auth0.min.esm.js:8:45717) [angular]
    at new WebAuth (auth0.min.esm.js:8:127902) [angular]
    at new AuthService (auth.service.ts:63:19) [angular]
    at Object.AuthService_Factory [as factory] (auth.service.ts:417:4) [angular]
    at R3Injector.hydrate (core.js:11291:1) [angular]
    at R3Injector.get (core.js:11113:1) [angular]
    at NgModuleRef$1.get (core.js:24245:1) [angular]
    at Object.get (core.js:23949:1) [angular]
    at getOrCreateInjectable (core.js:4079:1) [angular]
    at Module.ɵɵdirectiveInject (core.js:14653:1) [angular]
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:28:26) [angular]
    at getNodeInjectable (core.js:4184:1) [angular]
    at instantiateRootComponent (core.js:7966:1) [angular]
```

The same happens if I go inside the `dist/app` folder and run `python -m http.server` there to have it running on port 8000.

I think the problem could probably be solved if I had access to the **setup.bash** file.

Do you know how could I make this web app work locally?

I look forward to hearing from you.

**Comment by rubenanapu** [comment]
Alright.

I found the last version of that [setup.bash](https://github.com/gazebo-web/gazebosim-app/blob/5b39131964b191a4737c2c40e8fb0b34511ca6e6/setup.bash) file.

Now I'm able to run "**npm start**" locally after running "**source setup.bash**"

I see the file was removed on commit [6fb8fe71de21a0a6e722d68df351d09ddbda10d2](https://github.com/gazebo-web/gazebosim-app/commit/6fb8fe71de21a0a6e722d68df351d09ddbda10d2)

Thank God I found it before it was deleted: https://github.com/gazebo-web/gazebosim-app/blob/5b39131964b191a4737c2c40e8fb0b34511ca6e6/setup.bash
